package squidpony.squidgrid.fov;

import java.util.TreeMap;

/**
 *
 * @author Eben Howard - http://squidpony.com - eben@squidpony.com
 */
public class FOVDemoPanel extends javax.swing.JPanel {

    TreeMap<String, FOVSolver> fovs = new TreeMap<String, FOVSolver>();

    /**
     * Creates new form FOVDemoPanel
     */
    public FOVDemoPanel() {
        initComponents();
        fovs.put("Shadow Casting", new ShadowFOV());
        fovs.put("Spiral", new SpiralFOV());
        fovs.put("Ray Casting", new RayCastingFOV());

        fovComboBox.removeAllItems();
        for (String s : fovs.keySet()) {
            fovComboBox.addItem(s);
        }
        fovComboBox.setSelectedIndex(0);
    }

    public FOVSolver getFOVSolver() {
        return fovs.get((String) fovComboBox.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fovComboBox = new javax.swing.JComboBox();
        clearBox = new javax.swing.JButton();

        jLabel1.setText("FOV Solver");

        fovComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clearBox.setText("Clear FOV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fovComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fovComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton clearBox;
    private javax.swing.JComboBox fovComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
